name: Code Standards & Quality

on:
  workflow_call:
    inputs:
      run-build:
        type: boolean
        default: false

jobs:
  build:
    name: Check Code standards & Quality
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: 🛫 Checkout code
        uses: actions/checkout@v4

      - name: "📦 Install pnpm"
        uses: pnpm/action-setup@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔎 Lint code
        run: pnpm lint

      - name: 📝 Checking code format
        run: pnpm format:check

      - name: 💪 Type Checking
        run: pnpm  type-check

      - name: 🚀 Build the project
        if: ${{ inputs.run-build }}
        run: pnpm run build
