name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  code_quality:
    uses: ./.github/workflows/code-standards-checks.yml
    with:
      node-version: "20"
      run-build: true

  unit-tests:
    uses: ./.github/workflows/tests.yml
    with:
      node-version: "20"
